name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: amiorin/once-form-handler

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Download big-container
        run: docker pull ghcr.io/amiorin/big-container:latest
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Runs tests
        id: run_tests
        run: >-
          docker run
          --rm
          -u vscode
          -v /tmp:/tmp
          -e SSH_AUTH_SOCK=$SSH_AUTH_SOCK
          -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE
          ghcr.io/amiorin/big-container:latest
          fish -c 'cd $GITHUB_WORKSPACE
          && devenv shell clojure -X:test'

  # test locally
  # cat .github/workflows/ci.yml | jet -i yaml -o json | jq -r .jobs.test.steps[2].run | GITHUB_WORKSPACE=$(pwd) bash -s

  build-and-push:
    needs:
      - test
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
